services:
  node0: &node
    image: proof-net
    command: ["/node", "0", "config_docker.txt"]
    volumes:
     - ./receipts:/app/receipts
  node1:
    <<: *node
    command: ["/node", "1", "config_docker.txt"]
  node2:
    <<: *node
    command: ["/node", "2", "config_docker.txt"]
  node3:
    <<: *node
    command: ["/node", "3", "config_docker.txt"]