services:
  node0:
    image: proof-net
    command: ["/node", "0", "nw_config.txt", "acct_config.txt"]
    volumes:
      - ../messages/node0:/app/messages
      - ../receipts/node0:/app/receipts
       - ../state/node0:/app/state
      - ../keys/pvt/node0.key:/app/keys/pvt/pvt.key:ro
      - ../keys/pub:/app/keys/pub:ro
  node1:
    image: proof-net
    command: ["/node", "1", "nw_config.txt", "acct_config.txt"]
    volumes:
      - ../messages/node1:/app/messages
      - ../receipts/node1:/app/receipts
      - ../state/node1:/app/state
      - ../keys/pvt/node1.key:/app/keys/pvt/pvt.key:ro
      - ../keys/pub:/app/keys/pub:ro
  node2:
    image: proof-net
    command: ["/node", "2", "nw_config.txt", "acct_config.txt"]
    volumes:
      - ../messages/node2:/app/messages
      - ../receipts/node2:/app/receipts
      - ../state/node2:/app/state
      - ../keys/pvt/node2.key:/app/keys/pvt/pvt.key:ro
      - ../keys/pub:/app/keys/pub:ro
  node3:
    image: proof-net
    command: ["/node", "3", "nw_config.txt", "acct_config.txt"]
    volumes:
      - ../messages/node3:/app/messages
      - ../receipts/node3:/app/receipts
      - ../state/node3:/app/state
      - ../keys/pvt/node3.key:/app/keys/pvt/pvt.key:ro
      - ../keys/pub:/app/keys/pub:ro
  acct0:
    image: proof-net
    command: ["/acct", "1000", "nw_config.txt", "acct_config.txt"]
    volumes:
      - ../state/acct0:/app/state
      - ../keys/pvt/acct_common.key:/app/keys/pvt/acct_common.key:ro
      - ../keys/pub:/app/keys/pub:ro
  acct1:
    image: proof-net
    command: ["/acct", "1001", "nw_config.txt", "acct_config.txt"]
    volumes:
      - ../state/acct1:/app/state
      - ../keys/pvt/acct_common.key:/app/keys/pvt/acct_common.key:ro
      - ../keys/pub:/app/keys/pub:ro
